// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * craspeed_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * valuechanhe_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_116455110);    // assets/Frame 1 (2).png
LV_IMG_DECLARE(ui_img_rectangle_3_png);    // assets/Rectangle 3.png

// FONTS
LV_FONT_DECLARE(ui_font_speed14);
LV_FONT_DECLARE(ui_font_speed15);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
